### ISSUE TITLE
about the color box inside of terminal

### ISSUE THREAD

**Issue by Belmaj** [fehawen/rpg#1]
sorry sir if i ask you here i just really want to know how you made this im still confuse and i dont know how i can make this like yours
![Screenshot 2020-09-23 101055](https://user-images.githubusercontent.com/57773946/94092836-b3bb0c80-fda6-11ea-8bb9-d5a70ff6f604.png)
sorry sir if i disturb you i just really want to know this.. thanks if you notice this.

**Comment by Belmaj** [comment]
sorry for my bad english.

**Comment by fehawen** [comment]
Hey, no worries at all. Always happy to help. Have a look at the [reply](https://www.reddit.com/r/unixporn/comments/iyifoh/sowm_simplemindedness/g6efmwp?utm_source=share&utm_medium=web2x&context=3) I sent on reddit. If you still need help, let me know.
